# Site settings
title: Thoughts from the ether
description: > # this means to ignore newlines until "baseurl:"
  This is a recolection of my random ideas/thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://netguino.github.io" # the base hostname & protocol for your site
twitter_username: netguino
github_username:  netguino

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal